# Generated by Django 4.0.5 on 2022-06-21 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='exposure_end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='노출 종료 일자'),
        ),
        migrations.AddField(
            model_name='article',
            name='exposure_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='노출 시작 일자'),
        ),
    ]
