# Generated by Django 4.0.5 on 2022-06-22 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='상품사진')),
                ('desc', models.TextField(verbose_name='상품설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exposure_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='노출 시작 일자')),
                ('exposure_end_date', models.DateField(default=django.utils.timezone.now, verbose_name='노출 종료 일자')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
